# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: thodavid <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/11/11 11:09:12 by thodavid          #+#    #+#              #
#    Updated: 2025/03/05 15:20:01 by thodavid         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

################################################################################
## ARGUMENTS / VARIABLES

NAME		= libft.a

OBJS		= $(SRCS:.c=.o)

CC		= cc

CFLAGS		= -Wall -Wextra -Werror


################################################################################
## SOURCES

SRCS		= ft_atoi.c \
		  ft_bzero.c \
		  ft_calloc.c \
		  ft_isalnum.c \
		  ft_isalpha.c \
		  ft_isascii.c \
		  ft_isdigit.c \
		  ft_isprint.c \
		  ft_memchr.c \
		  ft_memcmp.c \
		  ft_memcpy.c \
		  ft_memmove.c \
		  ft_memset.c \
		  ft_strchr.c \
		  ft_strdup.c \
		  ft_strjoin.c \
		  ft_strlcat.c \
		  ft_strlcpy.c \
		  ft_strlen.c \
		  ft_strncmp.c \
		  ft_strnstr.c \
		  ft_strrchr.c \
		  ft_strtrim.c \
		  ft_substr.c \
		  ft_tolower.c \
		  ft_toupper.c \
		  ft_putchar_fd.c \
		  ft_putendl_fd.c \
		  ft_putstr_fd.c \
		  ft_putnbr_fd.c \
		  ft_split.c \
		  ft_striteri.c \
		  ft_strmapi.c \
		  ft_itoa.c \
		  ft_printf/ft_printf.c \
		  ft_printf/ft_printf.c \
		  ft_printf/ft_putadress.c \
		  ft_printf/ft_puthexa.c \
		  ft_printf/ft_putnbr.c \
		  ft_printf/ft_unsputnbr.c \
		  ft_printf/ft_putchar.c \
		  ft_printf/ft_puthexaupp.c \
		  ft_printf/ft_putstr.c


BSOURCES 	= ft_lstnew_bonus.c \
		  ft_lstadd_front_bonus.c \
		  ft_lstsize_bonus.c \
		  ft_lstlast_bonus.c \
		  ft_lstadd_back_bonus.c \
		  ft_lstdelone_bonus.c \
		  ft_lstclear_bonus.c \
		  ft_lstiter_bonus.c \
		  ft_lstmap_bonus.c \
	

OBJS		= $(SRCS:.c=.o)
BOBJ		= $(BSOURCES:.c=.o)

################################################################################
## REGLES

all: $(NAME)

$(NAME): $(OBJS)
	ar rcs $(NAME) $(OBJS)

bonus: $(OBJS) $(BOBJ)
	$(AR) -r $(NAME) $?

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@
clean:
	rm -f $(OBJS) $(BOBJ)

fclean: clean
	rm -f $(NAME)
	
re: fclean all

.PHONY: all bonus clean fclean re
